# Configuration for PR labeler

# Add 'documentation' label to any change to docs files
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - '**/*.md'
      - 'LICENSE*'

# Add 'test' label to any change to test files
test:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**'
      - '**/*_test.rs'
      - '**/test_*.rs'

# Add 'ci' label to any change to CI files
ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.github/dependabot.yml'
      - 'cliff.toml'
      - 'deny.toml'
      - 'release.toml'

# Add 'dependencies' label to any change to dependency files
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'Cargo.toml'
      - 'Cargo.lock'

# Add 'ui' label to any UI-related changes
ui:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/ui/**'
      - 'src/widgets/**'

# Add 'broker' label to any broker-related changes
broker:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/broker/**'

# Add 'models' label to any model changes
models:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/models/**'

# Add 'config' label to configuration changes
config:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/config.rs'
      - 'examples/*.toml'
      - '**/*.toml'

# Add 'performance' label if PR title contains performance-related keywords
performance:
  - head-branch: ['^perf', 'performance']

# Add 'breaking-change' label if PR title contains breaking change keywords
breaking-change:
  - head-branch: ['^break', 'breaking']
  - title: ['BREAKING', 'breaking change', 'breaking-change']

# Add 'bug' label if PR fixes a bug
bug:
  - head-branch: ['^fix', 'bugfix', 'hotfix']
  - title: ['fix:', 'bug:', 'bugfix:']

# Add 'feature' label for new features
feature:
  - head-branch: ['^feat', 'feature']
  - title: ['feat:', 'feature:']

# Add size labels based on the number of changes
size/XS:
  - changed-files:
    - file-count: ['< 5']
    - line-count: ['< 50']

size/S:
  - changed-files:
    - file-count: ['< 10']
    - line-count: ['< 200']

size/M:
  - changed-files:
    - file-count: ['< 30']
    - line-count: ['< 500']

size/L:
  - changed-files:
    - file-count: ['< 100']
    - line-count: ['< 1000']

size/XL:
  - changed-files:
    - file-count: ['>= 100']
    - line-count: ['>= 1000']