name: lazycelery
base: core22
version: '0.2.0'
summary: Terminal UI for monitoring and managing Celery workers and tasks
description: |
  LazyCelery is a terminal UI for monitoring and managing Celery workers and tasks, 
  inspired by lazydocker/lazygit. It provides real-time monitoring of your Celery 
  infrastructure with an intuitive terminal interface.

  Features:
  - Real-time monitoring of Celery workers and tasks
  - Task management (retry, revoke, purge queues)
  - Redis broker support with real Celery protocol integration
  - Intuitive terminal interface with vim-style navigation
  - Cross-platform support

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  lazycelery:
    command: bin/lazycelery
    plugs:
      - network
      - network-bind
      - home

parts:
  lazycelery:
    plugin: rust
    source: https://github.com/Fguedes90/lazycelery.git
    source-tag: v0.2.0
    rust-features: []
    build-packages:
      - build-essential
      - pkg-config
    override-build: |
      craftctl default
      # Strip the binary to reduce size
      strip $CRAFT_PART_INSTALL/bin/lazycelery